### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by iammini5** [whkailee/AccSensorRecorder#1]
@whkailee 
1. 需求没看懂， highest possible sample rate 是什么意思，只记录一个最大值？那每个文件是不是只有一条记录 ？
2. 不建议用work manager里面开loop，work manager 用于执行一次任务就结束了，建议在 activity 里面启动一个线程或者
couroutine 就行了。
3. SensorEventListener 可以直接放在 activity 里 就可以了，中间这个 AccSensorProvider 没啥必要。onSensorChanged 应该可以用，不需要一直读取
4.  第二条需求没实现

**Comment by whkailee** [comment]
Thanks Yi!
